### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: module 'plugins.status-line' not found:

### ISSUE THREAD

**Issue by eddyekofo94** [richin13/dotfiles#1]
I keep getting this error when I attempt to open Neovim. 

`Error detected while processing function ConfigStatusLine:
line    1:
E5108: Error executing lua [string ":lua"]:1: module 'plugins.status-line' not found:
        no field package.preload['plugins.status-line'`

It seems like my configuration, I followed your structure

**Comment by richin13** [comment]
Hey @eddyekofo94!

I could use some more info about your environment, specifically the following:

* OS
* nvim --version

Sometimes `stow` fail to create the symlinks, let's debug it and see if that's the case. Can you also share the output of the following steps:

```bash
cd ~/.config/nvim
file lua
ls -l
```

I was able to reproduce the issue by deleting the `plugins.status-line` module so most likely your symlink was not created. The above commands will help us confirm it 👍🏼

**Comment by eddyekofo94** [comment]
Well the problem is fixed, I couldn’t tell you how but I think it was a problem with my vim config. It’s all sorted now. Also I believe my understanding of Lua & Neovim is improving so my debugging abilities is improved.

**Comment by richin13** [comment]
That's great to hear!
